FROM postgres:15

RUN apt-get update && apt-get install -y locales && \
    sed -i '/ru_RU.UTF-8/s/^#//' /etc/locale.gen && \
    locale-gen && \
    update-locale LANG=ru_RU.UTF-8

ENV LANG ru_RU.UTF-8
ENV LC_ALL ru_RU.UTF-8
