# Конфигурация Docker Compose для разработки
services:
  # Сервис PostgreSQL для хранения данных
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sro_noso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass1964hfpf
      POSTGRES_INITDB_ARGS: "--locale=en_US.utf8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  # Сервис Redis для кеширования и FSM
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    environment:
      REDIS_PASSWORD: redispass
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

# Тома для хранения данных
volumes:
  postgres_data:
